{{- if and .Values.tls.create (not .Values.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poolmgrd.tlsSecretName" . }}
  labels:
    {{- include "poolmgrd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $filename, $content := .Values.tls.files }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
