// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: poolmgr/v1alpha1/hostadmin.proto

package poolmgrv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAdmin_DrainHost_FullMethodName   = "/poolmgr.v1alpha1.HostAdmin/DrainHost"
	HostAdmin_UndrainHost_FullMethodName = "/poolmgr.v1alpha1.HostAdmin/UndrainHost"
	HostAdmin_ListHosts_FullMethodName   = "/poolmgr.v1alpha1.HostAdmin/ListHosts"
)

// HostAdminClient is the client API for HostAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostAdmin manages the drain state of registered flintlock hosts. Draining a host stops
// the reconciler from placing new VMs there; existing VMs are unaffected and wind down
// through normal lease expiry or release.
type HostAdminClient interface {
	DrainHost(ctx context.Context, in *DrainHostRequest, opts ...grpc.CallOption) (*Host, error)
	UndrainHost(ctx context.Context, in *UndrainHostRequest, opts ...grpc.CallOption) (*Host, error)
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
}

type hostAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAdminClient(cc grpc.ClientConnInterface) HostAdminClient {
	return &hostAdminClient{cc}
}

func (c *hostAdminClient) DrainHost(ctx context.Context, in *DrainHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAdmin_DrainHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) UndrainHost(ctx context.Context, in *UndrainHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAdmin_UndrainHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, HostAdmin_ListHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAdminServer is the server API for HostAdmin service.
// All implementations should embed UnimplementedHostAdminServer
// for forward compatibility.
//
// HostAdmin manages the drain state of registered flintlock hosts. Draining a host stops
// the reconciler from placing new VMs there; existing VMs are unaffected and wind down
// through normal lease expiry or release.
type HostAdminServer interface {
	DrainHost(context.Context, *DrainHostRequest) (*Host, error)
	UndrainHost(context.Context, *UndrainHostRequest) (*Host, error)
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
}

// UnimplementedHostAdminServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAdminServer struct{}

func (UnimplementedHostAdminServer) DrainHost(context.Context, *DrainHostRequest) (*Host, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrainHost not implemented")
}
func (UnimplementedHostAdminServer) UndrainHost(context.Context, *UndrainHostRequest) (*Host, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndrainHost not implemented")
}
func (UnimplementedHostAdminServer) ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedHostAdminServer) testEmbeddedByValue() {}

// UnsafeHostAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAdminServer will
// result in compilation errors.
type UnsafeHostAdminServer interface {
	mustEmbedUnimplementedHostAdminServer()
}

func RegisterHostAdminServer(s grpc.ServiceRegistrar, srv HostAdminServer) {
	// If the following call pancis, it indicates UnimplementedHostAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAdmin_ServiceDesc, srv)
}

func _HostAdmin_DrainHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).DrainHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_DrainHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).DrainHost(ctx, req.(*DrainHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_UndrainHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndrainHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).UndrainHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_UndrainHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).UndrainHost(ctx, req.(*UndrainHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_ListHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAdmin_ServiceDesc is the grpc.ServiceDesc for HostAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poolmgr.v1alpha1.HostAdmin",
	HandlerType: (*HostAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DrainHost",
			Handler:    _HostAdmin_DrainHost_Handler,
		},
		{
			MethodName: "UndrainHost",
			Handler:    _HostAdmin_UndrainHost_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _HostAdmin_ListHosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poolmgr/v1alpha1/hostadmin.proto",
}
