// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: poolmgr/v1alpha1/hostadmin.proto

package poolmgrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DrainHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Reason is an optional free-text note recorded alongside the drain.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainHostRequest) Reset() {
	*x = DrainHostRequest{}
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainHostRequest) ProtoMessage() {}

func (x *DrainHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainHostRequest.ProtoReflect.Descriptor instead.
func (*DrainHostRequest) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostadmin_proto_rawDescGZIP(), []int{0}
}

func (x *DrainHostRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DrainHostRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UndrainHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndrainHostRequest) Reset() {
	*x = UndrainHostRequest{}
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndrainHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndrainHostRequest) ProtoMessage() {}

func (x *UndrainHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndrainHostRequest.ProtoReflect.Descriptor instead.
func (*UndrainHostRequest) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostadmin_proto_rawDescGZIP(), []int{1}
}

func (x *UndrainHostRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostadmin_proto_rawDescGZIP(), []int{2}
}

// HostStatus pairs a host's registry record with its current live VM count.
type HostStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Host  *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// ActiveVmCount is the number of non-terminal (not DELETING/FAILED) VMs currently placed
	// on this host, across all pools.
	ActiveVmCount int32 `protobuf:"varint,2,opt,name=active_vm_count,json=activeVmCount,proto3" json:"active_vm_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStatus) Reset() {
	*x = HostStatus{}
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatus) ProtoMessage() {}

func (x *HostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStatus.ProtoReflect.Descriptor instead.
func (*HostStatus) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostadmin_proto_rawDescGZIP(), []int{3}
}

func (x *HostStatus) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *HostStatus) GetActiveVmCount() int32 {
	if x != nil {
		return x.ActiveVmCount
	}
	return 0
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostStatus          `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostadmin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostadmin_proto_rawDescGZIP(), []int{4}
}

func (x *ListHostsResponse) GetHosts() []*HostStatus {
	if x != nil {
		return x.Hosts
	}
	return nil
}

var File_poolmgr_v1alpha1_hostadmin_proto protoreflect.FileDescriptor

var file_poolmgr_v1alpha1_hostadmin_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x1a, 0x1c, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x10, 0x44, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x12, 0x55, 0x6e, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x60, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2a,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x5f, 0x76, 0x6d, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x56, 0x6d, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x47, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x32, 0xf7, 0x01, 0x0a, 0x09,
	0x48, 0x6f, 0x73, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x47, 0x0a, 0x09, 0x44, 0x72, 0x61,
	0x69, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x72, 0x61, 0x69, 0x6e, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x6f,
	0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x4b, 0x0a, 0x0b, 0x55, 0x6e, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x24, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x55, 0x6e, 0x64, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67,
	0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x54, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x22, 0x2e, 0x70,
	0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2d,
	0x64, 0x65, 0x76, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_poolmgr_v1alpha1_hostadmin_proto_rawDescOnce sync.Once
	file_poolmgr_v1alpha1_hostadmin_proto_rawDescData []byte
)

func file_poolmgr_v1alpha1_hostadmin_proto_rawDescGZIP() []byte {
	file_poolmgr_v1alpha1_hostadmin_proto_rawDescOnce.Do(func() {
		file_poolmgr_v1alpha1_hostadmin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poolmgr_v1alpha1_hostadmin_proto_rawDesc), len(file_poolmgr_v1alpha1_hostadmin_proto_rawDesc)))
	})
	return file_poolmgr_v1alpha1_hostadmin_proto_rawDescData
}

var file_poolmgr_v1alpha1_hostadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_poolmgr_v1alpha1_hostadmin_proto_goTypes = []any{
	(*DrainHostRequest)(nil),   // 0: poolmgr.v1alpha1.DrainHostRequest
	(*UndrainHostRequest)(nil), // 1: poolmgr.v1alpha1.UndrainHostRequest
	(*ListHostsRequest)(nil),   // 2: poolmgr.v1alpha1.ListHostsRequest
	(*HostStatus)(nil),         // 3: poolmgr.v1alpha1.HostStatus
	(*ListHostsResponse)(nil),  // 4: poolmgr.v1alpha1.ListHostsResponse
	(*Host)(nil),               // 5: poolmgr.v1alpha1.Host
}
var file_poolmgr_v1alpha1_hostadmin_proto_depIdxs = []int32{
	5, // 0: poolmgr.v1alpha1.HostStatus.host:type_name -> poolmgr.v1alpha1.Host
	3, // 1: poolmgr.v1alpha1.ListHostsResponse.hosts:type_name -> poolmgr.v1alpha1.HostStatus
	0, // 2: poolmgr.v1alpha1.HostAdmin.DrainHost:input_type -> poolmgr.v1alpha1.DrainHostRequest
	1, // 3: poolmgr.v1alpha1.HostAdmin.UndrainHost:input_type -> poolmgr.v1alpha1.UndrainHostRequest
	2, // 4: poolmgr.v1alpha1.HostAdmin.ListHosts:input_type -> poolmgr.v1alpha1.ListHostsRequest
	5, // 5: poolmgr.v1alpha1.HostAdmin.DrainHost:output_type -> poolmgr.v1alpha1.Host
	5, // 6: poolmgr.v1alpha1.HostAdmin.UndrainHost:output_type -> poolmgr.v1alpha1.Host
	4, // 7: poolmgr.v1alpha1.HostAdmin.ListHosts:output_type -> poolmgr.v1alpha1.ListHostsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poolmgr_v1alpha1_hostadmin_proto_init() }
func file_poolmgr_v1alpha1_hostadmin_proto_init() {
	if File_poolmgr_v1alpha1_hostadmin_proto != nil {
		return
	}
	file_poolmgr_v1alpha1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poolmgr_v1alpha1_hostadmin_proto_rawDesc), len(file_poolmgr_v1alpha1_hostadmin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poolmgr_v1alpha1_hostadmin_proto_goTypes,
		DependencyIndexes: file_poolmgr_v1alpha1_hostadmin_proto_depIdxs,
		MessageInfos:      file_poolmgr_v1alpha1_hostadmin_proto_msgTypes,
	}.Build()
	File_poolmgr_v1alpha1_hostadmin_proto = out.File
	file_poolmgr_v1alpha1_hostadmin_proto_goTypes = nil
	file_poolmgr_v1alpha1_hostadmin_proto_depIdxs = nil
}
