// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: poolmgr/v1alpha1/hostagent.proto

package poolmgrv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hostagent_WaitReady_FullMethodName = "/poolmgr.v1alpha1.Hostagent/WaitReady"
	Hostagent_Run_FullMethodName       = "/poolmgr.v1alpha1.Hostagent/Run"
)

// HostagentClient is the client API for Hostagent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hostagent is implemented by poolmgr-hostagent, a per-flintlock-host sidecar that proxies
// guest-agent vsock calls (via the vsock-connect CLI) on behalf of the pool manager, which has
// no direct filesystem access to other hosts' /run/flintlock/*.vsock sockets.
type HostagentClient interface {
	// WaitReady blocks until the guest-agent at vsock_path responds to a ping, or returns
	// DEADLINE_EXCEEDED once timeout elapses.
	WaitReady(ctx context.Context, in *WaitReadyRequest, opts ...grpc.CallOption) (*WaitReadyResponse, error)
	// Run executes cmd via the guest-agent's exec, streaming stdout/stderr chunks back as they're
	// produced and finishing with an ExitCode message once the command completes.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResponse], error)
}

type hostagentClient struct {
	cc grpc.ClientConnInterface
}

func NewHostagentClient(cc grpc.ClientConnInterface) HostagentClient {
	return &hostagentClient{cc}
}

func (c *hostagentClient) WaitReady(ctx context.Context, in *WaitReadyRequest, opts ...grpc.CallOption) (*WaitReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitReadyResponse)
	err := c.cc.Invoke(ctx, Hostagent_WaitReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostagentClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hostagent_ServiceDesc.Streams[0], Hostagent_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hostagent_RunClient = grpc.ServerStreamingClient[RunResponse]

// HostagentServer is the server API for Hostagent service.
// All implementations should embed UnimplementedHostagentServer
// for forward compatibility.
//
// Hostagent is implemented by poolmgr-hostagent, a per-flintlock-host sidecar that proxies
// guest-agent vsock calls (via the vsock-connect CLI) on behalf of the pool manager, which has
// no direct filesystem access to other hosts' /run/flintlock/*.vsock sockets.
type HostagentServer interface {
	// WaitReady blocks until the guest-agent at vsock_path responds to a ping, or returns
	// DEADLINE_EXCEEDED once timeout elapses.
	WaitReady(context.Context, *WaitReadyRequest) (*WaitReadyResponse, error)
	// Run executes cmd via the guest-agent's exec, streaming stdout/stderr chunks back as they're
	// produced and finishing with an ExitCode message once the command completes.
	Run(*RunRequest, grpc.ServerStreamingServer[RunResponse]) error
}

// UnimplementedHostagentServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostagentServer struct{}

func (UnimplementedHostagentServer) WaitReady(context.Context, *WaitReadyRequest) (*WaitReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitReady not implemented")
}
func (UnimplementedHostagentServer) Run(*RunRequest, grpc.ServerStreamingServer[RunResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedHostagentServer) testEmbeddedByValue() {}

// UnsafeHostagentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostagentServer will
// result in compilation errors.
type UnsafeHostagentServer interface {
	mustEmbedUnimplementedHostagentServer()
}

func RegisterHostagentServer(s grpc.ServiceRegistrar, srv HostagentServer) {
	// If the following call pancis, it indicates UnimplementedHostagentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hostagent_ServiceDesc, srv)
}

func _Hostagent_WaitReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostagentServer).WaitReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hostagent_WaitReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostagentServer).WaitReady(ctx, req.(*WaitReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hostagent_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostagentServer).Run(m, &grpc.GenericServerStream[RunRequest, RunResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hostagent_RunServer = grpc.ServerStreamingServer[RunResponse]

// Hostagent_ServiceDesc is the grpc.ServiceDesc for Hostagent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hostagent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poolmgr.v1alpha1.Hostagent",
	HandlerType: (*HostagentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WaitReady",
			Handler:    _Hostagent_WaitReady_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Hostagent_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "poolmgr/v1alpha1/hostagent.proto",
}
