// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: poolmgr/v1alpha1/hostadmin.proto

package poolmgrv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAdmin_CordonHost_FullMethodName   = "/poolmgr.v1alpha1.HostAdmin/CordonHost"
	HostAdmin_UncordonHost_FullMethodName = "/poolmgr.v1alpha1.HostAdmin/UncordonHost"
	HostAdmin_ListHosts_FullMethodName    = "/poolmgr.v1alpha1.HostAdmin/ListHosts"
	HostAdmin_AddHost_FullMethodName      = "/poolmgr.v1alpha1.HostAdmin/AddHost"
	HostAdmin_UpdateHost_FullMethodName   = "/poolmgr.v1alpha1.HostAdmin/UpdateHost"
	HostAdmin_RemoveHost_FullMethodName   = "/poolmgr.v1alpha1.HostAdmin/RemoveHost"
	HostAdmin_GetHost_FullMethodName      = "/poolmgr.v1alpha1.HostAdmin/GetHost"
)

// HostAdminClient is the client API for HostAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostAdmin manages the registry of flintlock hosts and their cordon state. Cordoning a
// host stops the reconciler from placing new VMs there; existing VMs are unaffected and
// wind down through normal lease expiry or release.
type HostAdminClient interface {
	CordonHost(ctx context.Context, in *CordonHostRequest, opts ...grpc.CallOption) (*Host, error)
	UncordonHost(ctx context.Context, in *UncordonHostRequest, opts ...grpc.CallOption) (*Host, error)
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
	// AddHost registers a new host. Unless skip_validation is set, the manager first dials
	// it and checks its flintlock version, and stores nothing if either fails.
	AddHost(ctx context.Context, in *AddHostRequest, opts ...grpc.CallOption) (*Host, error)
	// UpdateHost replaces an existing host's address and TLS settings and redials it.
	UpdateHost(ctx context.Context, in *UpdateHostRequest, opts ...grpc.CallOption) (*Host, error)
	// RemoveHost unregisters a host. It fails while any pool spec names the host in
	// flintlock_hosts, or while any VM or in-flight placement is still counted against it.
	RemoveHost(ctx context.Context, in *RemoveHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*HostStatus, error)
}

type hostAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAdminClient(cc grpc.ClientConnInterface) HostAdminClient {
	return &hostAdminClient{cc}
}

func (c *hostAdminClient) CordonHost(ctx context.Context, in *CordonHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAdmin_CordonHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) UncordonHost(ctx context.Context, in *UncordonHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAdmin_UncordonHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, HostAdmin_ListHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) AddHost(ctx context.Context, in *AddHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAdmin_AddHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) UpdateHost(ctx context.Context, in *UpdateHostRequest, opts ...grpc.CallOption) (*Host, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Host)
	err := c.cc.Invoke(ctx, HostAdmin_UpdateHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) RemoveHost(ctx context.Context, in *RemoveHostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HostAdmin_RemoveHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAdminClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*HostStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostStatus)
	err := c.cc.Invoke(ctx, HostAdmin_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAdminServer is the server API for HostAdmin service.
// All implementations should embed UnimplementedHostAdminServer
// for forward compatibility.
//
// HostAdmin manages the registry of flintlock hosts and their cordon state. Cordoning a
// host stops the reconciler from placing new VMs there; existing VMs are unaffected and
// wind down through normal lease expiry or release.
type HostAdminServer interface {
	CordonHost(context.Context, *CordonHostRequest) (*Host, error)
	UncordonHost(context.Context, *UncordonHostRequest) (*Host, error)
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
	// AddHost registers a new host. Unless skip_validation is set, the manager first dials
	// it and checks its flintlock version, and stores nothing if either fails.
	AddHost(context.Context, *AddHostRequest) (*Host, error)
	// UpdateHost replaces an existing host's address and TLS settings and redials it.
	UpdateHost(context.Context, *UpdateHostRequest) (*Host, error)
	// RemoveHost unregisters a host. It fails while any pool spec names the host in
	// flintlock_hosts, or while any VM or in-flight placement is still counted against it.
	RemoveHost(context.Context, *RemoveHostRequest) (*emptypb.Empty, error)
	GetHost(context.Context, *GetHostRequest) (*HostStatus, error)
}

// UnimplementedHostAdminServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAdminServer struct{}

func (UnimplementedHostAdminServer) CordonHost(context.Context, *CordonHostRequest) (*Host, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CordonHost not implemented")
}
func (UnimplementedHostAdminServer) UncordonHost(context.Context, *UncordonHostRequest) (*Host, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UncordonHost not implemented")
}
func (UnimplementedHostAdminServer) ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedHostAdminServer) AddHost(context.Context, *AddHostRequest) (*Host, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHost not implemented")
}
func (UnimplementedHostAdminServer) UpdateHost(context.Context, *UpdateHostRequest) (*Host, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHost not implemented")
}
func (UnimplementedHostAdminServer) RemoveHost(context.Context, *RemoveHostRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveHost not implemented")
}
func (UnimplementedHostAdminServer) GetHost(context.Context, *GetHostRequest) (*HostStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedHostAdminServer) testEmbeddedByValue() {}

// UnsafeHostAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAdminServer will
// result in compilation errors.
type UnsafeHostAdminServer interface {
	mustEmbedUnimplementedHostAdminServer()
}

func RegisterHostAdminServer(s grpc.ServiceRegistrar, srv HostAdminServer) {
	// If the following call pancis, it indicates UnimplementedHostAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAdmin_ServiceDesc, srv)
}

func _HostAdmin_CordonHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CordonHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).CordonHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_CordonHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).CordonHost(ctx, req.(*CordonHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_UncordonHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncordonHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).UncordonHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_UncordonHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).UncordonHost(ctx, req.(*UncordonHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_ListHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_AddHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).AddHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_AddHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).AddHost(ctx, req.(*AddHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_UpdateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).UpdateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_UpdateHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).UpdateHost(ctx, req.(*UpdateHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_RemoveHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).RemoveHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_RemoveHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).RemoveHost(ctx, req.(*RemoveHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAdmin_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAdminServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAdmin_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAdminServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAdmin_ServiceDesc is the grpc.ServiceDesc for HostAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poolmgr.v1alpha1.HostAdmin",
	HandlerType: (*HostAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CordonHost",
			Handler:    _HostAdmin_CordonHost_Handler,
		},
		{
			MethodName: "UncordonHost",
			Handler:    _HostAdmin_UncordonHost_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _HostAdmin_ListHosts_Handler,
		},
		{
			MethodName: "AddHost",
			Handler:    _HostAdmin_AddHost_Handler,
		},
		{
			MethodName: "UpdateHost",
			Handler:    _HostAdmin_UpdateHost_Handler,
		},
		{
			MethodName: "RemoveHost",
			Handler:    _HostAdmin_RemoveHost_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _HostAdmin_GetHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poolmgr/v1alpha1/hostadmin.proto",
}
