// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: poolmgr/v1alpha1/hostagent.proto

package poolmgrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitReadyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VsockPath is the host-local Unix-domain-socket path from flintlock's
	// MicroVMStatus.vsock_path.
	VsockPath string `protobuf:"bytes,1,opt,name=vsock_path,json=vsockPath,proto3" json:"vsock_path,omitempty"`
	// Timeout bounds how long to keep retrying the ping before giving up.
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitReadyRequest) Reset() {
	*x = WaitReadyRequest{}
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitReadyRequest) ProtoMessage() {}

func (x *WaitReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitReadyRequest.ProtoReflect.Descriptor instead.
func (*WaitReadyRequest) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostagent_proto_rawDescGZIP(), []int{0}
}

func (x *WaitReadyRequest) GetVsockPath() string {
	if x != nil {
		return x.VsockPath
	}
	return ""
}

func (x *WaitReadyRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type WaitReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitReadyResponse) Reset() {
	*x = WaitReadyResponse{}
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitReadyResponse) ProtoMessage() {}

func (x *WaitReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitReadyResponse.ProtoReflect.Descriptor instead.
func (*WaitReadyResponse) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostagent_proto_rawDescGZIP(), []int{1}
}

type RunRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	VsockPath string                 `protobuf:"bytes,1,opt,name=vsock_path,json=vsockPath,proto3" json:"vsock_path,omitempty"`
	// Cmd is the command and its arguments, e.g. ["echo", "hi"] -- passed through to
	// `vsock-connect exec ... -- <cmd...>` without a shell.
	Cmd []string `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	// Timeout bounds how long the command may run before it's killed and Run returns
	// DEADLINE_EXCEEDED.
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostagent_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetVsockPath() string {
	if x != nil {
		return x.VsockPath
	}
	return ""
}

func (x *RunRequest) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *RunRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type RunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*RunResponse_StdoutChunk
	//	*RunResponse_StderrChunk
	//	*RunResponse_ExitCode
	Output        isRunResponse_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poolmgr_v1alpha1_hostagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_poolmgr_v1alpha1_hostagent_proto_rawDescGZIP(), []int{3}
}

func (x *RunResponse) GetOutput() isRunResponse_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RunResponse) GetStdoutChunk() []byte {
	if x != nil {
		if x, ok := x.Output.(*RunResponse_StdoutChunk); ok {
			return x.StdoutChunk
		}
	}
	return nil
}

func (x *RunResponse) GetStderrChunk() []byte {
	if x != nil {
		if x, ok := x.Output.(*RunResponse_StderrChunk); ok {
			return x.StderrChunk
		}
	}
	return nil
}

func (x *RunResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Output.(*RunResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isRunResponse_Output interface {
	isRunResponse_Output()
}

type RunResponse_StdoutChunk struct {
	StdoutChunk []byte `protobuf:"bytes,1,opt,name=stdout_chunk,json=stdoutChunk,proto3,oneof"`
}

type RunResponse_StderrChunk struct {
	StderrChunk []byte `protobuf:"bytes,2,opt,name=stderr_chunk,json=stderrChunk,proto3,oneof"`
}

type RunResponse_ExitCode struct {
	// ExitCode is sent as the final message in the stream once the command completes.
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*RunResponse_StdoutChunk) isRunResponse_Output() {}

func (*RunResponse_StderrChunk) isRunResponse_Output() {}

func (*RunResponse_ExitCode) isRunResponse_Output() {}

var File_poolmgr_v1alpha1_hostagent_proto protoreflect.FileDescriptor

var file_poolmgr_v1alpha1_hostagent_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x10, 0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x73, 0x6f, 0x63,
	0x6b, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x73,
	0x6f, 0x63, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x12, 0x33, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x13, 0x0a, 0x11,
	0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x72, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x76, 0x73, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x73, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64,
	0x12, 0x33, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x5f,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x73,
	0x74, 0x64, 0x6f, 0x75, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x1d, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x08,
	0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0xa7, 0x01, 0x0a, 0x09, 0x48, 0x6f, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x54, 0x0a, 0x09, 0x57, 0x61, 0x69, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x12, 0x22, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67,
	0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x03,
	0x52, 0x75, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2d, 0x64, 0x65, 0x76,
	0x2f, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x3b, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x67, 0x72, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_poolmgr_v1alpha1_hostagent_proto_rawDescOnce sync.Once
	file_poolmgr_v1alpha1_hostagent_proto_rawDescData []byte
)

func file_poolmgr_v1alpha1_hostagent_proto_rawDescGZIP() []byte {
	file_poolmgr_v1alpha1_hostagent_proto_rawDescOnce.Do(func() {
		file_poolmgr_v1alpha1_hostagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poolmgr_v1alpha1_hostagent_proto_rawDesc), len(file_poolmgr_v1alpha1_hostagent_proto_rawDesc)))
	})
	return file_poolmgr_v1alpha1_hostagent_proto_rawDescData
}

var file_poolmgr_v1alpha1_hostagent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_poolmgr_v1alpha1_hostagent_proto_goTypes = []any{
	(*WaitReadyRequest)(nil),    // 0: poolmgr.v1alpha1.WaitReadyRequest
	(*WaitReadyResponse)(nil),   // 1: poolmgr.v1alpha1.WaitReadyResponse
	(*RunRequest)(nil),          // 2: poolmgr.v1alpha1.RunRequest
	(*RunResponse)(nil),         // 3: poolmgr.v1alpha1.RunResponse
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_poolmgr_v1alpha1_hostagent_proto_depIdxs = []int32{
	4, // 0: poolmgr.v1alpha1.WaitReadyRequest.timeout:type_name -> google.protobuf.Duration
	4, // 1: poolmgr.v1alpha1.RunRequest.timeout:type_name -> google.protobuf.Duration
	0, // 2: poolmgr.v1alpha1.Hostagent.WaitReady:input_type -> poolmgr.v1alpha1.WaitReadyRequest
	2, // 3: poolmgr.v1alpha1.Hostagent.Run:input_type -> poolmgr.v1alpha1.RunRequest
	1, // 4: poolmgr.v1alpha1.Hostagent.WaitReady:output_type -> poolmgr.v1alpha1.WaitReadyResponse
	3, // 5: poolmgr.v1alpha1.Hostagent.Run:output_type -> poolmgr.v1alpha1.RunResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poolmgr_v1alpha1_hostagent_proto_init() }
func file_poolmgr_v1alpha1_hostagent_proto_init() {
	if File_poolmgr_v1alpha1_hostagent_proto != nil {
		return
	}
	file_poolmgr_v1alpha1_hostagent_proto_msgTypes[3].OneofWrappers = []any{
		(*RunResponse_StdoutChunk)(nil),
		(*RunResponse_StderrChunk)(nil),
		(*RunResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poolmgr_v1alpha1_hostagent_proto_rawDesc), len(file_poolmgr_v1alpha1_hostagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poolmgr_v1alpha1_hostagent_proto_goTypes,
		DependencyIndexes: file_poolmgr_v1alpha1_hostagent_proto_depIdxs,
		MessageInfos:      file_poolmgr_v1alpha1_hostagent_proto_msgTypes,
	}.Build()
	File_poolmgr_v1alpha1_hostagent_proto = out.File
	file_poolmgr_v1alpha1_hostagent_proto_goTypes = nil
	file_poolmgr_v1alpha1_hostagent_proto_depIdxs = nil
}
