// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: poolmgr/v1alpha1/lease.proto

package poolmgrv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lease_ClaimVM_FullMethodName   = "/poolmgr.v1alpha1.Lease/ClaimVM"
	Lease_Heartbeat_FullMethodName = "/poolmgr.v1alpha1.Lease/Heartbeat"
	Lease_ReleaseVM_FullMethodName = "/poolmgr.v1alpha1.Lease/ReleaseVM"
)

// LeaseClient is the client API for Lease service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Lease lets a consumer claim a VM from a pool and manage its lease.
type LeaseClient interface {
	// ClaimVM atomically picks an AVAILABLE VM from the named pool. Fails with
	// RESOURCE_EXHAUSTED when no VM is AVAILABLE.
	ClaimVM(ctx context.Context, in *ClaimVMRequest, opts ...grpc.CallOption) (*ClaimVMResponse, error)
	// Heartbeat is keyed by lease_id and extends the lease's expiry.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReleaseVM(ctx context.Context, in *ReleaseVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type leaseClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaseClient(cc grpc.ClientConnInterface) LeaseClient {
	return &leaseClient{cc}
}

func (c *leaseClient) ClaimVM(ctx context.Context, in *ClaimVMRequest, opts ...grpc.CallOption) (*ClaimVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimVMResponse)
	err := c.cc.Invoke(ctx, Lease_ClaimVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Lease_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseClient) ReleaseVM(ctx context.Context, in *ReleaseVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Lease_ReleaseVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaseServer is the server API for Lease service.
// All implementations should embed UnimplementedLeaseServer
// for forward compatibility.
//
// Lease lets a consumer claim a VM from a pool and manage its lease.
type LeaseServer interface {
	// ClaimVM atomically picks an AVAILABLE VM from the named pool. Fails with
	// RESOURCE_EXHAUSTED when no VM is AVAILABLE.
	ClaimVM(context.Context, *ClaimVMRequest) (*ClaimVMResponse, error)
	// Heartbeat is keyed by lease_id and extends the lease's expiry.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReleaseVM(context.Context, *ReleaseVMRequest) (*emptypb.Empty, error)
}

// UnimplementedLeaseServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaseServer struct{}

func (UnimplementedLeaseServer) ClaimVM(context.Context, *ClaimVMRequest) (*ClaimVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimVM not implemented")
}
func (UnimplementedLeaseServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedLeaseServer) ReleaseVM(context.Context, *ReleaseVMRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseVM not implemented")
}
func (UnimplementedLeaseServer) testEmbeddedByValue() {}

// UnsafeLeaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaseServer will
// result in compilation errors.
type UnsafeLeaseServer interface {
	mustEmbedUnimplementedLeaseServer()
}

func RegisterLeaseServer(s grpc.ServiceRegistrar, srv LeaseServer) {
	// If the following call pancis, it indicates UnimplementedLeaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lease_ServiceDesc, srv)
}

func _Lease_ClaimVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServer).ClaimVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lease_ClaimVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServer).ClaimVM(ctx, req.(*ClaimVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lease_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lease_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lease_ReleaseVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServer).ReleaseVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lease_ReleaseVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServer).ReleaseVM(ctx, req.(*ReleaseVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lease_ServiceDesc is the grpc.ServiceDesc for Lease service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lease_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poolmgr.v1alpha1.Lease",
	HandlerType: (*LeaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimVM",
			Handler:    _Lease_ClaimVM_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Lease_Heartbeat_Handler,
		},
		{
			MethodName: "ReleaseVM",
			Handler:    _Lease_ReleaseVM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poolmgr/v1alpha1/lease.proto",
}
